import {CONFIG,PALETTE} from '../config.js';
import {Input} from '../systems/Input.js';
import {GameTime} from '../systems/Time.js';
import {Inventory} from '../systems/Inventory.js';
import {SaveManager} from '../systems/Save.js';
import {Player} from '../entities/Player.js';
import {NPC} from '../entities/NPC.js';
import {ITEMS,SHOPS} from '../data/items.js';
import {BUILDINGS,TREES,COLLIDERS,INTERIORS,LANDMARKS} from '../data/world.js';
import {NPC_DEFS} from '../data/npcs.js';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export class Game{
 constructor(canvas){this.c=canvas;this.ctx=canvas.getContext('2d');this.ctx.imageSmoothingEnabled=false;this.input=new Input();this.save=new SaveManager();this.time=new GameTime();this.inventory=new Inventory();this.player=new Player(300,1420);this.npcs=NPC_DEFS.map(d=>new NPC(d));this.money=120;this.scene='world';this.interiorId=null;this.running=false;this.dialogue=null;this.talked=new Set();this.camera={x:0,y:0};this.selected=0;this.ui=this.bindUI();this.last=performance.now();this.autosave=0;this.toastUntil=0;this.audio={ctx:null,volume:.45};this.resize();addEventListener('resize',()=>this.resize());requestAnimationFrame(t=>this.loop(t));}
 bindUI(){const q=id=>document.getElementById(id),ui={title:q('title-screen'),hud:q('hud'),clock:q('clock'),daypart:q('daypart'),money:q('money'),hotbar:q('hotbar'),prompt:q('prompt'),toast:q('toast'),dialogue:q('dialogue'),dialogueName:q('dialogue-name'),dialogueText:q('dialogue-text'),inventory:q('inventory'),inventoryGrid:q('inventory-grid'),itemDetails:q('item-details'),shop:q('shop'),shopName:q('shop-name'),shopSubtitle:q('shop-subtitle'),shopGrid:q('shop-grid'),settings:q('settings'),fade:q('fade'),continueBtn:q('continue-game')};q('new-game').onclick=()=>this.startNew();q('continue-game').onclick=()=>this.continueGame();q('settings-button').onclick=()=>ui.settings.classList.remove('hidden');q('fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();q('volume').oninput=e=>{this.audio.volume=+e.target.value;localStorage.setItem(CONFIG.SETTINGS_KEY,JSON.stringify({volume:this.audio.volume}))};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).classList.add('hidden'));ui.continueBtn.disabled=!this.save.exists();try{const s=JSON.parse(localStorage.getItem(CONFIG.SETTINGS_KEY));if(s?.volume>=0){this.audio.volume=s.volume;q('volume').value=s.volume}}catch{}return ui}
 resize(){const dpr=Math.min(devicePixelRatio||1,2),w=innerWidth,h=innerHeight;this.c.width=Math.floor(w*dpr);this.c.height=Math.floor(h*dpr);this.viewW=w;this.viewH=h;this.dpr=dpr;this.ctx.setTransform(dpr,0,0,dpr,0,0);this.ctx.imageSmoothingEnabled=false}
 startNew(){this.save.clear();this.time=new GameTime();this.inventory=new Inventory();this.inventory.add('bread',2);this.inventory.add('apple',3);this.player=new Player(300,1420);this.money=120;this.scene='world';this.interiorId=null;this.talked.clear();this.begin()}
 continueGame(){const s=this.save.load();if(!s)return this.startNew();this.time=new GameTime(s.time);this.inventory=new Inventory(18,s.inventory);this.player=new Player(s.player.x,s.player.y);this.player.dir=s.player.dir||'south';this.money=s.money??120;this.scene=s.scene||'world';this.interiorId=s.interiorId||null;this.talked=new Set(s.talked||[]);this.begin()}
 begin(){this.running=true;this.ui.title.classList.add('hidden');this.ui.hud.classList.remove('hidden');this.playTone(220,.04);this.syncUI()}
 playTone(freq=330,dur=.06){if(this.audio.volume<=0)return;try{this.audio.ctx??=new AudioContext();const o=this.audio.ctx.createOscillator(),g=this.audio.ctx.createGain();o.type='square';o.frequency.value=freq;g.gain.value=.025*this.audio.volume;o.connect(g).connect(this.audio.ctx.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,this.audio.ctx.currentTime+dur);o.stop(this.audio.ctx.currentTime+dur)}catch{}}
 loop(t){const dt=Math.min(50,t-this.last);this.last=t;if(this.running){this.update(dt);this.render()}requestAnimationFrame(n=>this.loop(n))}
 update(dt){if(this.input.hit('i','I','Tab'))this.toggleInventory();if(this.input.hit('Escape'))this.closePanels();const locked=this.isLocked();this.time.update(locked?0:dt);this.updateNPCs(dt);this.player.update(dt,this.input,(x,y,r)=>this.blocked(x,y,r),locked);this.handleInteractions();this.updateCamera(dt);this.autosave+=dt;if(this.autosave>CONFIG.AUTOSAVE_MS){this.save.save(this);this.autosave=0}if(this.toastUntil&&performance.now()>this.toastUntil){this.ui.toast.classList.add('hidden');this.toastUntil=0}this.syncUI();this.input.endFrame()}
 isLocked(){return !!this.dialogue||!this.ui.inventory.classList.contains('hidden')||!this.ui.shop.classList.contains('hidden')||!this.ui.settings.classList.contains('hidden')}
 closePanels(){this.dialogue=null;this.ui.dialogue.classList.add('hidden');this.ui.inventory.classList.add('hidden');this.ui.shop.classList.add('hidden');this.ui.settings.classList.add('hidden')}
 toggleInventory(){if(this.dialogue)return;if(this.ui.inventory.classList.contains('hidden')){this.ui.shop.classList.add('hidden');this.renderInventory();this.ui.inventory.classList.remove('hidden')}else this.ui.inventory.classList.add('hidden')}
 blocked(x,y,r){const bounds=this.scene==='world'?{w:CONFIG.WORLD_W,h:CONFIG.WORLD_H}:INTERIORS[this.interiorId];if(x-r<0||y-r<0||x+r>bounds.w||y+r>bounds.h)return true;const list=this.scene==='world'?COLLIDERS:INTERIORS[this.interiorId].walls.concat(INTERIORS[this.interiorId].props);return list.some(o=>x+r>o.x&&x-r<o.x+o.w&&y+r>o.y&&y-r<o.y+o.h)}
 getSchedule(def){const m=this.time.minutes;for(const [a,b,...rest] of def.schedule){const toMin=s=>{const [h,x]=s.split(':').map(Number);return h*60+x};if(m>=toMin(a)&&m<toMin(b))return rest}return def.schedule[def.schedule.length-1].slice(2)}
 updateNPCs(dt){for(const n of this.npcs){const s=this.getSchedule(n);if(typeof s[0]==='string'){const scene=s[0],x=s[1],y=s[2];if(n.scene!==scene)n.setScene(scene,x,y);else if(n.scene===this.scene)n.moveToward(dt,x,y,(a,b,r)=>this.npcBlocked(n,a,b,r))}else{if(n.scene!=='world')n.setScene('world',s[0],s[1]);else n.moveToward(dt,s[0],s[1],(a,b,r)=>this.npcBlocked(n,a,b,r))}}}
 npcBlocked(n,x,y,r){const list=n.scene==='world'?COLLIDERS:INTERIORS[n.scene]?.walls.concat(INTERIORS[n.scene]?.props||[])||[];return list.some(o=>x+r>o.x&&x-r<o.x+o.w&&y+r>o.y&&y-r<o.y+o.h)}
 interactable(){let best=null,bd=999;if(this.scene==='world'){for(const b of BUILDINGS){const d=dist(this.player,{x:b.door.x+b.door.w/2,y:b.door.y+b.door.h/2});if(b.interior&&d<62&&d<bd){best={type:'door',label:`Enter ${b.name}`,data:b};bd=d}}}else{const room=INTERIORS[this.interiorId],exit={x:room.exit.x+room.exit.w/2,y:room.exit.y+room.exit.h/2};const d=dist(this.player,exit);if(d<65){best={type:'exit',label:'Leave building'};bd=d}if(room.shop&&this.player.y<235){best={type:'shop',label:`Browse ${SHOPS[room.shop].name}`,shop:room.shop};bd=20}}
 for(const n of this.npcs){if(n.scene===this.scene){const d=dist(this.player,n);if(d<55&&d<bd){best={type:'npc',label:`Talk to ${n.name}`,data:n};bd=d}}}return best}
 handleInteractions(){const it=this.interactable();if(it){this.ui.prompt.textContent=`E — ${it.label}`;this.ui.prompt.classList.remove('hidden')}else this.ui.prompt.classList.add('hidden');if(this.dialogue&&(this.input.hit('e','E',' ','Enter'))){this.advanceDialogue();return}if(!it||this.isLocked()||!this.input.hit('e','E'))return;this.playTone(360,.04);if(it.type==='door')this.enter(it.data);else if(it.type==='exit')this.exitInterior();else if(it.type==='shop')this.openShop(it.shop);else if(it.type==='npc')this.talk(it.data)}
 enter(b){this.transition(()=>{this.scene=b.interior;this.interiorId=b.interior;const r=INTERIORS[b.interior];this.player.x=r.spawn.x;this.player.y=r.spawn.y;this.player.dir='north';this.save.save(this)})}
 exitInterior(){const b=BUILDINGS.find(x=>x.interior===this.interiorId);this.transition(()=>{this.scene='world';this.interiorId=null;this.player.x=b.door.x+b.door.w/2;this.player.y=b.door.y+b.door.h+35;this.player.dir='south';this.save.save(this)})}
 transition(fn){this.ui.fade.classList.add('on');setTimeout(()=>{fn();this.ui.fade.classList.remove('on')},210)}
 talk(n){const extra=this.talked.has(n.id)?[]:[`You are new around Brackenvale, aren't you? I am ${n.name}. ${n.role[0].toUpperCase()+n.role.slice(1)}, more or less.`];const lines=[...extra,...n.dialogue];if(this.time.daypart==='Night')lines.push('Best not linger too long. Even a quiet village has a different face after dark.');this.talked.add(n.id);this.dialogue={name:n.name,lines,index:0};this.showDialogue()}
 showDialogue(){this.ui.dialogueName.textContent=this.dialogue.name;this.ui.dialogueText.textContent=this.dialogue.lines[this.dialogue.index];this.ui.dialogue.classList.remove('hidden')}
 advanceDialogue(){this.dialogue.index++;this.playTone(300,.025);if(this.dialogue.index>=this.dialogue.lines.length){this.dialogue=null;this.ui.dialogue.classList.add('hidden')}else this.showDialogue()}
 openShop(id){const s=SHOPS[id];this.ui.shopName.textContent=s.name;this.ui.shopSubtitle.textContent=s.subtitle;this.ui.shopGrid.innerHTML='';s.stock.forEach(([itemId,price])=>{const d=ITEMS[itemId],el=document.createElement('div');el.className='shop-item';el.innerHTML=`<div class="icon">${d.icon}</div><div><strong>${d.name}</strong><small>${d.description}</small></div><div class="price">◉ ${price}</div>`;el.onclick=()=>this.buy(itemId,price);this.ui.shopGrid.append(el)});this.ui.shop.classList.remove('hidden')}
 buy(id,price){if(this.money<price)return this.toast('Not enough coin.');if(!this.inventory.add(id,1))return this.toast('Your satchel is full.');this.money-=price;this.playTone(650,.08);this.toast(`${ITEMS[id].name} purchased.`);this.renderInventory();this.save.save(this)}
 toast(msg){this.ui.toast.textContent=msg;this.ui.toast.classList.remove('hidden');this.toastUntil=performance.now()+1600}
 renderInventory(){this.ui.inventoryGrid.innerHTML='';this.inventory.slots.forEach((s,i)=>{const el=document.createElement('div');el.className='inventory-slot';if(s){const d=ITEMS[s.id];el.innerHTML=`<span class="icon">${d.icon}</span><span class="qty">${s.qty>1?s.qty:''}</span>`;el.onclick=()=>{this.ui.itemDetails.innerHTML=`<h3>${d.name}</h3><p>${d.description}</p><p><small>${d.category.toUpperCase()} · value ◉ ${d.value}</small></p>`}}this.ui.inventoryGrid.append(el)});this.renderHotbar()}
 renderHotbar(){this.ui.hotbar.innerHTML='';for(let i=0;i<8;i++){const s=this.inventory.slots[i],el=document.createElement('div');el.className='hot-slot'+(i===this.selected?' selected':'');if(s){const d=ITEMS[s.id];el.innerHTML=`<b>${d.icon}</b><small>${s.qty>1?s.qty:''}</small>`}this.ui.hotbar.append(el)}}
 syncUI(){this.ui.clock.textContent=this.time.text;this.ui.daypart.textContent=this.time.daypart;this.ui.money.textContent=this.money;if(!this.ui.inventory.classList.contains('hidden'))this.renderInventory();else this.renderHotbar()}
 updateCamera(dt){const b=this.scene==='world'?{w:CONFIG.WORLD_W,h:CONFIG.WORLD_H}:INTERIORS[this.interiorId];const tx=clamp(this.player.x-this.viewW/2,0,Math.max(0,b.w-this.viewW)),ty=clamp(this.player.y-this.viewH/2,0,Math.max(0,b.h-this.viewH));const k=1-Math.pow(.001,dt/1000);this.camera.x+=(tx-this.camera.x)*k;this.camera.y+=(ty-this.camera.y)*k}
 render(){const c=this.ctx;c.setTransform(this.dpr,0,0,this.dpr,0,0);c.clearRect(0,0,this.viewW,this.viewH);c.save();c.translate(-Math.round(this.camera.x),-Math.round(this.camera.y));if(this.scene==='world')this.drawWorld(c);else this.drawInterior(c,INTERIORS[this.interiorId]);this.drawEntities(c);c.restore();this.drawLighting(c)}
 drawWorld(c){c.fillStyle=PALETTE.grass;c.fillRect(0,0,CONFIG.WORLD_W,CONFIG.WORLD_H);for(let x=30;x<CONFIG.WORLD_W;x+=67)for(let y=35;y<CONFIG.WORLD_H;y+=73){c.fillStyle=((x+y)%3)?'#67864b':'#55743e';c.fillRect(x,y,2,5);c.fillRect(x+4,y+1,2,4)}this.path(c,[[1050,0,105,1760],[0,500,2400,115],[750,980,1120,90],[250,900,95,650],[1460,560,95,940],[1960,500,100,1000]]);c.fillStyle=PALETTE.water;c.fillRect(0,310,780,150);c.fillRect(1890,310,510,150);c.fillRect(1875,310,525,690);for(let y=325;y<1000;y+=24){c.fillStyle=PALETTE.water2;c.fillRect(1890,y+Math.sin(y)*6,160,3)}c.fillStyle='#75614a';c.fillRect(780,365,1110,65);for(let x=790;x<1880;x+=18){c.fillStyle=x%36?'#9c835e':'#6f5b45';c.fillRect(x,368,12,59)}this.drawFields(c);for(const b of BUILDINGS)this.drawBuilding(c,b);for(const t of TREES)this.drawTree(c,t.x,t.y);this.drawWell(c,1112,455);for(const l of LANDMARKS){c.font='bold 12px Georgia';c.textAlign='center';c.fillStyle='#28201699';c.fillText(l.label,l.x,l.y)}this.drawRuins(c,2120,1420)}
 path(c,rects){for(const [x,y,w,h] of rects){c.fillStyle=PALETTE.path;c.fillRect(x,y,w,h);c.fillStyle=PALETTE.path2;for(let i=0;i<Math.max(w,h);i+=31)c.fillRect(x+(i*13)%Math.max(1,w-5),y+(i*7)%Math.max(1,h-3),5,3)}}
 drawFields(c){for(let y=940;y<1370;y+=42)for(let x=80;x<620;x+=36){c.fillStyle='#806a43';c.fillRect(x,y,30,28);c.fillStyle='#c2a74c';c.fillRect(x+13,y-7,3,24);c.fillRect(x+6,y+2,16,2)}c.strokeStyle='#6c5133';c.lineWidth=6;c.strokeRect(65,915,570,480)}
 drawBuilding(c,b){c.fillStyle='#6d6559';c.fillRect(b.x,b.y+55,b.w,b.h-55);c.fillStyle=b.roof;c.beginPath();c.moveTo(b.x-15,b.y+65);c.lineTo(b.x+b.w/2,b.y);c.lineTo(b.x+b.w+15,b.y+65);c.closePath();c.fill();c.fillStyle='#3a2922';c.fillRect(b.door.x,b.door.y,b.door.w,b.door.h);c.fillStyle='#d2a95f';c.fillRect(b.door.x+7,b.door.y+7,b.door.w-14,b.door.h-7);for(let x=b.x+32;x<b.x+b.w-35;x+=82){c.fillStyle='#d8b56b';c.fillRect(x,b.y+92,28,30);c.fillStyle='#405d66';c.fillRect(x+4,b.y+96,20,22)}c.font='bold 13px Georgia';c.textAlign='center';c.fillStyle='#2c2119';c.fillRect(b.x+b.w/2-75,b.y+b.h+8,150,22);c.fillStyle='#ead9a9';c.fillText(b.name,b.x+b.w/2,b.y+b.h+24)}
 drawTree(c,x,y){c.fillStyle=PALETTE.trunk;c.fillRect(x-8,y+12,16,36);c.fillStyle='#29452f';c.beginPath();c.arc(x,y,34,0,Math.PI*2);c.fill();c.fillStyle=PALETTE.tree2;c.beginPath();c.arc(x-12,y-12,24,0,Math.PI*2);c.arc(x+16,y-8,24,0,Math.PI*2);c.fill();c.fillStyle='#6f8e52';c.fillRect(x-18,y-26,5,5);c.fillRect(x+14,y-20,4,4)}
 drawWell(c,x,y){c.fillStyle='#5c5c56';c.fillRect(x-34,y-14,68,34);c.fillStyle='#353c3d';c.fillRect(x-25,y-8,50,20);c.fillStyle='#72523c';c.fillRect(x-42,y-54,7,55);c.fillRect(x+35,y-54,7,55);c.fillStyle='#70423a';c.fillRect(x-50,y-61,100,12)}
 drawRuins(c,x,y){c.fillStyle='#62615a';c.fillRect(x-90,y,24,115);c.fillRect(x+50,y-20,24,135);c.fillRect(x-90,y,164,20);c.fillRect(x-20,y+75,70,20);c.fillStyle='#52584b';c.fillRect(x-90,y+35,8,22)}
 drawInterior(c,r){c.fillStyle=r.floor;c.fillRect(0,0,r.w,r.h);for(let x=50;x<r.w;x+=48){c.fillStyle='#ffffff0a';c.fillRect(x,44,2,r.h-88)}for(const w of r.walls){c.fillStyle='#574334';c.fillRect(w.x,w.y,w.w,w.h);c.fillStyle='#7e684e';c.fillRect(w.x,w.y,w.w,8)}for(const p of r.props)this.drawProp(c,p);c.fillStyle='#2a1e17';c.fillRect(r.exit.x,r.exit.y,r.exit.w,r.exit.h);c.fillStyle='#b48a51';c.fillRect(r.exit.x+12,r.exit.y+6,r.exit.w-24,r.exit.h-6);c.font='bold 14px Georgia';c.textAlign='center';c.fillStyle='#2a2017';c.fillText(r.name,r.w/2,28)}
 drawProp(c,p){const col={bed:'#6f4b4f',fireplace:'#51453d',table:'#755238',chest:'#6b4b2f',counter:'#6f4b34',shelf:'#6b503b',display:'#80603d',forge:'#3b3836',anvil:'#4c5052',rack:'#5d4a38',bar:'#704a33',pew:'#6d5038',altar:'#8a826e'}[p.type]||'#66513c';c.fillStyle=col;c.fillRect(p.x,p.y,p.w,p.h);c.fillStyle='#ffffff18';c.fillRect(p.x+4,p.y+4,p.w-8,5);if(['forge','fireplace'].includes(p.type)){c.fillStyle='#ee8b3e';c.fillRect(p.x+p.w*.35,p.y+p.h*.35,p.w*.3,p.h*.35);c.fillStyle='#ffd36c';c.fillRect(p.x+p.w*.45,p.y+p.h*.43,p.w*.12,p.h*.2)}}
 drawEntities(c){const list=[];for(const n of this.npcs)if(n.scene===this.scene)list.push({kind:'npc',y:n.y,obj:n});list.push({kind:'player',y:this.player.y,obj:this.player});list.sort((a,b)=>a.y-b.y);for(const e of list)this.drawPerson(c,e.obj,e.kind==='player');if(this.scene==='world'){for(const t of TREES.filter(t=>t.y>this.player.y-10&&t.y<this.player.y+50)){c.fillStyle='#355638cc';c.beginPath();c.arc(t.x,t.y-6,34,0,Math.PI*2);c.fill()}}}
 drawPerson(c,p,isPlayer=false){const x=p.x,y=p.y,step=Math.sin(p.walk)*2;c.save();c.translate(Math.round(x),Math.round(y));c.fillStyle='#0004';c.beginPath();c.ellipse(0,12,12,5,0,0,Math.PI*2);c.fill();const skin=isPlayer?'#dca272':p.skin,hair=isPlayer?'#563d2c':p.hair,clothes=isPlayer?'#425f57':p.clothes;c.fillStyle=clothes;c.fillRect(-10,-4,20,22);c.fillStyle='#342a25';c.fillRect(-9+step,16,7,8);c.fillRect(2-step,16,7,8);c.fillStyle=skin;c.fillRect(-8,-19,16,16);c.fillStyle=hair;c.fillRect(-9,-22,18,7);if(p.dir==='west'){c.fillStyle='#211';c.fillRect(-8,-13,2,2)}else if(p.dir==='east'){c.fillStyle='#211';c.fillRect(6,-13,2,2)}else if(p.dir==='south'){c.fillStyle='#211';c.fillRect(-5,-13,2,2);c.fillRect(3,-13,2,2)}c.fillStyle=isPlayer?'#c9a85c':'#9d7a50';c.fillRect(-12,0,4,13);c.fillRect(8,0,4,13);c.restore();if(!isPlayer){c.font='11px Georgia';c.textAlign='center';c.fillStyle='#1b1510aa';c.fillRect(x-40,y+27,80,16);c.fillStyle='#eadfbf';c.fillText(p.name,x,y+39)}}
 drawLighting(c){const h=this.time.h;if(h>=20||h<6){const alpha=h>=22||h<5?.42:.27;c.save();c.globalCompositeOperation='source-over';c.fillStyle=`rgba(17,25,45,${alpha})`;c.fillRect(0,0,this.viewW,this.viewH);c.restore()}else if(h>=18){c.fillStyle='rgba(123,73,48,.12)';c.fillRect(0,0,this.viewW,this.viewH)}}
}
